export type User = {
  id: string;
  name: string;
  emoji?: string;
  familyGroupId?: string;
};

export type FamilyGroup = {
  id: string;
  name: string;
  memberIds: string[];
};

export type AccountMode = '누적형' | '차감형';
export type AccountType = '현금' | '계좌' | '체크카드' | '현금카드';
export type Sharing = 'private' | 'shared-r' | 'shared-rw';
export type EditPolicy = 'author-only' | 'any-sharer';

// UI 표기용 메타 (이모지/라벨). 확장 대비 객체로 관리.
export const ACCOUNT_TYPE_META: Record<AccountType, { emoji: string; label: string; hint: string }> = {
  현금: { emoji: '💵', label: '현금', hint: '지갑 속 실물 현금' },
  계좌: { emoji: '🏦', label: '계좌', hint: '은행 입출금/적금/예금' },
  체크카드: { emoji: '💳', label: '체크카드', hint: '계좌에서 즉시 결제' },
  현금카드: { emoji: '🏧', label: '현금카드', hint: 'ATM 입출금 전용 카드' },
};
export const ACCOUNT_TYPES: AccountType[] = ['현금', '계좌', '체크카드', '현금카드'];

export type RecurringDeposit = {
  id: string;
  interval: 'monthly' | 'weekly';
  dayOfMonth?: number;
  dayOfWeek?: number;
  amount: number;
  source: string;
};

export type LowBalanceAlert = {
  amount?: number;   // 이 금액 이하로 떨어지면 알림
  percent?: number;  // 배정 대비 이 % 이하로 남으면 알림 (0-100)
  notify?: 'owner' | 'all'; // 알림 대상: 본인만 | 공유받은 사용자 모두 (기본 'owner')
};

export type Account = {
  id: string;
  ownerId: string;
  name: string;
  emoji?: string;
  type?: AccountType;         // 결제/보유 수단. 미설정은 '계좌' 취급 (기존 데이터 호환).
  mode: AccountMode;
  initialBalance?: number;
  recurringDeposits: RecurringDeposit[];
  goalId?: string;
  sharing: Sharing;
  sharedWith: string[];
  editPolicy: EditPolicy;
  categories: string[];
  budgetAllocations: Record<string, Record<string, number>>; // { [month]: { [category]: allocated } } — 카테고리별 세부 배정
  monthlyBudget?: Record<string, number>;                    // { [month]: 총예산 } — 차감형 계좌의 월 총 예산. 카테고리 배정합과 별개로 "덩어리 예산" 지정.
  settlementReminder?: { dayOfMonth: number; enabled: boolean };
  lowBalanceAlert?: LowBalanceAlert;  // 차감형 전용. 미설정이면 알림 없음
  createdAt: string;
};

export type Transaction = {
  id: string;
  accountId: string;
  authorId: string;
  date: string;              // 'YYYY-MM-DD'
  amount: number;            // + inflow / - outflow
  category?: string;
  source?: string;           // 자유 입력 출처 라벨 (입금 시)
  memo?: string;
  autoGenerated?: boolean;   // 정기입금 자동 생성
  isSupplement?: boolean;    // 차감형 전용: 예산 추경 여부 (양수 거래만 의미). 체크 시 예산에 합산.
};

export type GoalMode = '누적형' | '차감형';
export type GoalStatus = '진행중' | '완료' | '실패';

export type Goal = {
  id: string;
  ownerType: 'user' | 'family';
  ownerId: string;
  name: string;
  emoji?: string;
  mode?: GoalMode;           // 기본 '누적형' (기존 데이터 호환)
  startAmount?: number;      // 시작 금액. 누적형 기본 0, 차감형은 출발점(부채 등)
  targetAmount: number;      // 목표 금액. 누적형: 도달 상한, 차감형: 도달 하한
  startDate?: string;        // 'YYYY-MM' — 목표 시작 시점
  targetDate: string;        // 'YYYY-MM' — 목표 달성 예정 시점
  linkedAccountIds: string[];
  status?: GoalStatus;       // 기본 '진행중' (기존 데이터 호환)
};

export type SettlementDecision =
  | { type: 'keep' }
  | { type: 'move'; toCategory: string }
  | { type: 'return' };
