export type User = {
  id: string;
  name: string;
  emoji?: string;
  familyGroupId?: string;
};

export type FamilyGroup = {
  id: string;
  name: string;
  memberIds: string[];
};

export type AccountMode = '누적형' | '차감형';
export type AccountType = '현금' | '계좌' | '체크카드' | '현금카드';
export type Sharing = 'private' | 'shared-r' | 'shared-rw';
export type EditPolicy = 'author-only' | 'any-sharer';

// UI 표기용 메타 (이모지/라벨). 확장 대비 객체로 관리.
export const ACCOUNT_TYPE_META: Record<AccountType, { emoji: string; label: string; hint: string }> = {
  현금: { emoji: '💵', label: '현금', hint: '지갑 속 실물 현금' },
  계좌: { emoji: '🏦', label: '계좌', hint: '은행 입출금/적금/예금' },
  체크카드: { emoji: '💳', label: '체크카드', hint: '계좌에서 즉시 결제' },
  현금카드: { emoji: '🏧', label: '현금카드', hint: 'ATM 입출금 전용 카드' },
};
export const ACCOUNT_TYPES: AccountType[] = ['현금', '계좌', '체크카드', '현금카드'];

export type RecurringDeposit = {
  id: string;
  interval: 'monthly' | 'weekly';
  dayOfMonth?: number;
  dayOfWeek?: number;
  amount: number;
  source: string;
};

export type LowBalanceAlert = {
  amount?: number;   // 이 금액 이하로 떨어지면 알림
  percent?: number;  // 배정 대비 이 % 이하로 남으면 알림 (0-100)
  notify?: 'owner' | 'all'; // 알림 대상: 본인만 | 공유받은 사용자 모두 (기본 'owner')
};

export type Account = {
  id: string;
  ownerId: string;
  name: string;
  emoji?: string;
  type?: AccountType;         // 결제/보유 수단. 미설정은 '계좌' 취급 (기존 데이터 호환).
  mode: AccountMode;
  initialBalance?: number;
  recurringDeposits: RecurringDeposit[];
  goalId?: string;
  sharing: Sharing;
  sharedWith: string[];
  editPolicy: EditPolicy;
  categories: string[];
  budgetAllocations: Record<string, Record<string, number>>; // { [month]: { [category]: allocated } } — 카테고리별 세부 배정
  monthlyBudget?: Record<string, number>;                    // { [month]: 총예산 } — 차감형 계좌의 월 총 예산. 카테고리 배정합과 별개로 "덩어리 예산" 지정.
  settlementReminder?: { dayOfMonth: number; enabled: boolean };
  lowBalanceAlert?: LowBalanceAlert;  // 차감형 전용. 미설정이면 알림 없음
  createdAt: string;
};

export type Transaction = {
  id: string;
  accountId: string;
  authorId: string;
  date: string;              // 'YYYY-MM-DD'
  amount: number;            // + inflow / - outflow
  category?: string;
  source?: string;           // 자유 입력 출처 라벨 (입금 시)
  memo?: string;
  autoGenerated?: boolean;   // 정기입금/반복규칙 자동 생성
  sourceRuleId?: string;     // 반복 규칙으로 생성된 경우 원본 규칙 id
  isSupplement?: boolean;    // 차감형 전용: 예산 추경 여부 (양수 거래만 의미). 체크 시 예산에 합산.
};

export type RecurringInterval =
  | 'daily'
  | 'weekdays'
  | 'weekends'
  | 'weekly'
  | 'biweekly'
  | 'every4weeks'
  | 'monthly'
  | 'every2months'
  | 'every3months'
  | 'every4months'
  | 'every5months'
  | 'every6months'
  | 'yearly';

export const RECURRING_INTERVAL_META: Record<RecurringInterval, { label: string }> = {
  daily: { label: '매일' },
  weekdays: { label: '평일 (월-금)' },
  weekends: { label: '주말 (토-일)' },
  weekly: { label: '매주' },
  biweekly: { label: '2주마다' },
  every4weeks: { label: '4주마다' },
  monthly: { label: '매월' },
  every2months: { label: '2개월마다' },
  every3months: { label: '3개월마다' },
  every4months: { label: '4개월마다' },
  every5months: { label: '5개월마다' },
  every6months: { label: '6개월마다' },
  yearly: { label: '매년' },
};

export type RecurringRule = {
  id: string;
  ownerId: string;
  accountId: string;
  kind: 'expense' | 'deposit';
  amount: number;            // 양수. 저장 시 kind에 따라 부호 결정
  interval: RecurringInterval;
  startDate: string;         // 'YYYY-MM-DD'
  endDate?: string;          // 'YYYY-MM-DD' (옵션, 무기한)
  category?: string;
  source?: string;
  memo?: string;
  isSupplement?: boolean;    // 차감형+입금일 때만 의미
  lastRunDate?: string;      // 마지막으로 자동 생성한 날짜 (YYYY-MM-DD)
  enabled: boolean;
  createdAt: string;
};

export type GoalMode = '누적형' | '차감형';
export type GoalStatus = '진행중' | '완료' | '실패';

export type Goal = {
  id: string;
  ownerType: 'user' | 'family';
  ownerId: string;
  name: string;
  emoji?: string;
  mode?: GoalMode;           // 기본 '누적형' (기존 데이터 호환)
  startAmount?: number;      // 시작 금액. 누적형 기본 0, 차감형은 출발점(부채 등)
  targetAmount: number;      // 목표 금액. 누적형: 도달 상한, 차감형: 도달 하한
  startDate?: string;        // 'YYYY-MM' — 목표 시작 시점
  targetDate: string;        // 'YYYY-MM' — 목표 달성 예정 시점
  linkedAccountIds: string[];
  status?: GoalStatus;       // 기본 '진행중' (기존 데이터 호환)
};

export type SettlementDecision =
  | { type: 'keep' }
  | { type: 'move'; toCategory: string }
  | { type: 'return' };

// 전역 카테고리 택소노미 — 모든 계좌/거래가 공유하는 카테고리 정의.
// 지출/수입으로 구분되며 메인 카테고리 아래에 서브를 가짐.
// 거래의 `category` 필드에는 서브 label이 저장됨.
export type CategoryKind = 'expense' | 'income';

export type SubCategory = {
  id: string;
  label: string;
};

export type MainCategory = {
  id: string;
  kind: CategoryKind;
  emoji: string;
  label: string;
  subs: SubCategory[];
};

export const CATEGORY_KIND_META: Record<CategoryKind, { emoji: string; label: string }> = {
  expense: { emoji: '💸', label: '지출' },
  income: { emoji: '💰', label: '수입' },
};

// 거래 입력 폼의 필드 식별자. 향후 설정에서 필드별 필수 여부를 사용자가
// 토글할 수 있도록 키 단위로 관리. 'date'는 항상 값이 있으므로 제외.
export type TxField = 'amount' | 'category' | 'memo' | 'source';

// 페이지별 표시 가능 섹션 키. 각 페이지의 /settings/{page}-view 에서 토글.
// 모든 키는 '미설정/true = 표시', false = 숨김 규칙을 따름.
export type HomeSection = 'goals' | 'accounts';
export type AccountsSection = 'mine' | 'shared';
export type CalendarSection = 'viewToggle' | 'search';
export type StatsSection =
  | 'summary'
  | 'monthly'
  | 'net'
  | 'category'
  | 'accountType'
  | 'activeGoals';

// 사용자 환경설정. 향후 /settings/preferences 같은 페이지에서 편집.
// 기본값은 '아무것도 강제하지 않음'으로 빠른 입력에 우선순위.
export type Preferences = {
  // 거래 추가/수정 시 필수로 강제할 필드. true면 비어있으면 저장 불가.
  // 비어있는 키나 false는 모두 '선택'으로 취급.
  txRequired: Partial<Record<TxField, boolean>>;
  // 거래의 category가 undefined일 때 화면에 표시할 라벨.
  // 통계/필터 그룹핑 키도 이 라벨로 통일됨.
  uncategorizedLabel: string;
  // 페이지별 섹션 표시 토글. false 만 숨김(빈 상태도 함께), 미설정/true 모두 표시.
  homeSections: Partial<Record<HomeSection, boolean>>;
  accountsSections: Partial<Record<AccountsSection, boolean>>;
  calendarSections: Partial<Record<CalendarSection, boolean>>;
  statsSections: Partial<Record<StatsSection, boolean>>;
};

export const DEFAULT_PREFERENCES: Preferences = {
  // 기본은 모든 필드가 선택 — 빠른 입력 우선.
  // 향후 /settings/preferences에서 사용자가 필드별 필수 여부를 토글 가능.
  txRequired: {},
  uncategorizedLabel: '미분류',
  homeSections: {},
  accountsSections: {},
  calendarSections: {},
  statsSections: {},
};
